spring:
  application:
    name: oneuldo
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
