package com.example.onuldo.domain.user.enums;

public enum NotificationType {
    VERIFICATION_DEADLINE,
    VERIFICATION_APPROVED,
    VERIFICATION_REJECTED,
    PARTY_MEMBER_VERIFIED,
    CHALLENGE_START,
    CHALLENGE_END_REMINDER,
    REFUND_COMPLETE,
    PARTY_SETTLEMENT_COMPLETE
}
